### ISSUE TITLE
Larger files do not work in browser anymore

### ISSUE THREAD

**Issue by ktk** [zazuko/csv-validate#10]
I'm not sure it's related to the file-size but for many files I tried validating on the deployed version at https://zazuko.com/csv-validate/ recently seem to fail with an error.

Among others, I tested two versions of the same file, one with 100 lines, one with 10 lines. The one with 10 lines works, while the one with 100 lines fails with the error I get on every somewhat larger file: ` TypeError: Object(...) is not a function`.

I'm pretty sure this used to work just fine on files that now fail.

For testing, the larger one of the two files fails, the smaller one validates.

[didok-10.csv](https://github.com/zazuko/csv-validate/files/9879546/didok-10.csv)
[didok-100.csv](https://github.com/zazuko/csv-validate/files/9879547/didok-100.csv)

**Comment by cristianvasquez** [comment]
Where is the source code of the interface deployed at  https://zazuko.com/csv-validate/ ?

I'm testing the UI provided in this repo, which doesn't fail. 

![image](https://user-images.githubusercontent.com/361916/198318254-dcc51bad-b8f5-44d1-acdd-686055aec579.png)

**Comment by ktk** [comment]
@cristianvasquez as in you deployed it locally and it works?

**Comment by cristianvasquez** [comment]
It works locally, but it's another UI implementation. 

I ignore where is the source code of https://zazuko.com/csv-validate/

**Comment by ludovicm67** [comment]
This issue was only impacting the version deployed in our website.
I managed to provide a fix.
I will close this issue.
